import { Crown, Shield, Sparkles, Users, Download, MessageCircle } from "lucide-react";
import { news, site } from "@/data/site";
export default function Home(){return <main>
 <section className="hero-bg flex min-h-[860px] items-end justify-center px-5 pb-20 pt-28 text-center">
  <div className="max-w-4xl"><div className="h-[330px] md:h-[440px]"/><p className="text-sm font-bold tracking-[.42em] text-[#e1b85a]">FORGE YOUR LEGACY</p><h1 className="sr-only">Levincia</h1><p className="mx-auto mt-5 max-w-2xl text-lg text-slate-300">A community-driven 317 experience built around adventure, progression and memorable content.</p>
  <div className="mt-8 flex flex-wrap justify-center gap-4"><a href="/levincia-website/download/" className="flex items-center gap-2 rounded-md bg-[#d8aa45] px-7 py-4 font-bold text-black shadow-gold"><Download size={19}/> DOWNLOAD</a><a href={site.discord} className="flex items-center gap-2 rounded-md border border-[#4da3ff66] bg-[#10213a] px-7 py-4 font-bold text-white shadow-blue"><MessageCircle size={19}/> JOIN DISCORD</a></div></div>
 </section>
 <section className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-5 md:grid-cols-3">{[[Shield,"Custom Adventure","Fresh progression and content designed around the Levincia community."],[Crown,"Meaningful Progression","Build your account, tackle challenges and chase prestigious unlocks."],[Users,"Community First","Stay connected through Discord, events and regular development updates."]].map(([Icon,t,d]:any)=><div key={t} className="glass rounded-xl p-7"><Icon className="mb-5 text-[#d8aa45]"/><h2 className="text-2xl font-bold">{t}</h2><p className="mt-3 text-slate-400">{d}</p></div>)}</div></section>
 <section className="border-y border-white/10 bg-white/[.02]"><div className="mx-auto max-w-7xl px-5 py-20"><div className="mb-8 flex items-end justify-between"><div><p className="text-xs tracking-[.3em] text-[#d8aa45]">THE LATEST</p><h2 className="mt-2 text-4xl font-black gold-text">News & Updates</h2></div><a href="/levincia-website/news/" className="text-sm text-[#76b8ff]">View all →</a></div><div className="grid gap-5 md:grid-cols-3">{news.map(n=><article className="glass rounded-xl p-6" key={n.title}><span className="text-xs font-bold tracking-wider text-[#4da3ff]">{n.tag}</span><h3 className="mt-3 text-xl font-bold">{n.title}</h3><p className="mt-2 text-xs text-slate-500">{n.date}</p><p className="mt-4 text-sm leading-6 text-slate-400">{n.body}</p></article>)}</div></div></section>
 <section className="mx-auto max-w-5xl px-5 py-24 text-center"><Sparkles className="mx-auto text-[#d8aa45]"/><h2 className="mt-5 text-4xl font-black gold-text">Your adventure starts here.</h2><p className="mx-auto mt-4 max-w-2xl text-slate-400">Join the Levincia community and follow development while the server and launcher come together.</p><a href={site.discord} className="mt-8 inline-block rounded-md border border-[#d8aa4566] px-7 py-3 font-bold">JOIN THE COMMUNITY</a></section>
 </main>}
